name:                mild
version:             0.1.0.0
github:              "tmciver/mild"
license:             BSD3
author:              "Tim McIver"
maintainer:          "tim@timmciver.com"
copyright:           "2019 Tim McIver"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tmciver/mild#readme>

dependencies:
- base >= 4.7 && < 5
- hsexif

library:
  source-dirs: src

executables:
  mild-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mild

tests:
  mild-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mild
